FROM node:20-alpine AS builder
WORKDIR /builder
COPY package.json package-lock.json ./
RUN npm ci
COPY index.js math.js ./

FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --from=builder /builder/index.js ./
COPY --from=builder /builder/math.js ./
CMD ["node", "index.js"]
